<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>io.github.microsphere-projects</groupId>
        <artifactId>microsphere-hibernate</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.microsphere-projects</groupId>
    <artifactId>microsphere-hibernate-parent</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>Microsphere :: Hibernate :: Parent</name>
    <description>Microsphere Hibernate Parent</description>

    <properties>
        <microsphere-spring-cloud.version>0.1.25</microsphere-spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <!-- Hibernate Dependencies -->
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-core</artifactId>
                <version>${hibernate.version}</version>
            </dependency>

            <!-- Microsphere Spring Cloud Dependencies -->
            <dependency>
                <groupId>io.github.microsphere-projects</groupId>
                <artifactId>microsphere-spring-cloud-dependencies</artifactId>
                <version>${microsphere-spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>hibernate-5.6</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <hibernate.version>5.6.15.Final</hibernate.version>
            </properties>
        </profile>

        <profile>
            <id>hibernate-5.5</id>
            <properties>
                <hibernate.version>5.5.9.Final</hibernate.version>
            </properties>
        </profile>

        <profile>
            <id>hibernate-5.4</id>
            <properties>
                <hibernate.version>5.4.33.Final</hibernate.version>
            </properties>
        </profile>

        <profile>
            <id>hibernate-5.3</id>
            <properties>
                <hibernate.version>5.3.38.Final</hibernate.version>
            </properties>
        </profile>

        <profile>
            <id>hibernate-5.2</id>
            <properties>
                <hibernate.version>5.2.18.Final</hibernate.version>
            </properties>
        </profile>

        <profile>
            <id>hibernate-5.1</id>
            <properties>
                <hibernate.version>5.1.9.Final</hibernate.version>
            </properties>
        </profile>

        <profile>
            <id>hibernate-5.0</id>
            <properties>
                <hibernate.version>5.0.9.Final</hibernate.version>
            </properties>
        </profile>

    </profiles>

</project>
